# ---------------------------------------------------------------------
# Function to add config defines to a list that depends on a namespace variable #defines that match
# the namespace can later be written out to a file
# ---------------------------------------------------------------------
function(add_config_define_namespace)
  set(options UNDEFINE)
  set(one_value_args DEFINE NAMESPACE)
  set(multi_value_args VALUE)
  cmake_parse_arguments(OPTION "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})

  # Global property name to store the defines for this namespace
  set(DEF_VAR CONFIG_DEFINITIONS_${OPTION_NAMESPACE})

  # to avoid extra trailing spaces (no value), use an if check
  if(OPTION_VALUE)
    set_property(GLOBAL APPEND PROPERTY ${DEF_VAR} "${OPTION_DEFINE} ${OPTION_VALUE}")
  else()
    set_property(GLOBAL APPEND PROPERTY ${DEF_VAR} "${OPTION_DEFINE}")
  endif()

  # if the user has set UNDEFINE, it means we must #undef the var before setting it
  if(OPTION_UNDEFINE)
    set_property(GLOBAL APPEND PROPERTY ${DEF_VAR} "#undef ${OPTION_DEFINE}")
  endif()

endfunction()

# ---------------------------------------------------------------------
# Function to write out all the config defines for a given namespace into a config file
# ---------------------------------------------------------------------
function(write_config_defines_file)
  set(options)
  set(one_value_args TEMPLATE NAMESPACE FILENAME)
  set(multi_value_args)
  cmake_parse_arguments(OPTION "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})

  get_property(DEFINITIONS_VAR GLOBAL PROPERTY CONFIG_DEFINITIONS_${OPTION_NAMESPACE})

  if(DEFINED DEFINITIONS_VAR)
    list(SORT DEFINITIONS_VAR)
    list(REMOVE_DUPLICATES DEFINITIONS_VAR)
  endif()

  set(config_defines "\n")
  foreach(def ${DEFINITIONS_VAR})
    if("${def}" MATCHES "^#undef")
      string(REGEX MATCH "#undef (.+)" _ "${def}")
      set(undef_var "${CMAKE_MATCH_1}")
      set(undef_string "#if defined(${undef_var})\n# undef ${undef_var}\n#endif\n\n")
      set(config_defines "${config_defines}${undef_string}")
    else()
      set(config_defines "${config_defines}#define ${def}\n")
    endif()
  endforeach()

  # if the user has not specified a template, generate a proper header file
  if(NOT OPTION_TEMPLATE)
    string(TOUPPER ${OPTION_NAMESPACE} NAMESPACE_UPPER)
    set(PREAMBLE
        "\n" "// Do not edit this file! It has been generated by the cmake configuration step.\n"
        "\n" "#ifndef GROX_CONFIG_${NAMESPACE_UPPER}_HPP\n"
        "#define GROX_CONFIG_${NAMESPACE_UPPER}_HPP\n"
    )
    set(TEMP_FILENAME "${PROJECT_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/${NAMESPACE_UPPER}")
    file(WRITE ${TEMP_FILENAME} ${PREAMBLE} ${config_defines} "#endif\n")
    configure_file("${TEMP_FILENAME}" "${OPTION_FILENAME}" COPYONLY)
    file(REMOVE "${TEMP_FILENAME}")
  else()
    configure_file("${OPTION_TEMPLATE}" "${OPTION_FILENAME}" @ONLY)
  endif()
endfunction()
